# 是否开启跨服模式
# 若false则使用本地文件存储模式
# 若true则需要HamsterService前置
useBC: true

# 若开启跨服模式，则需要配置datasource
datasource:
  driver: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/mc1.12.2-germ?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
  user: root
  password: Root123...

currencyTypes:
  # 货币ID
  "金币":
    # 是否允许转账
    canTransfer: true
  "一周年活动代币":
    canTransfer: false
  "比特币":
    canTransfer: true

# 开启这个选项前请先确保服务器安装了Vault前置
vault:
  # 是否挂接 Vault 经济系统
  hook: true
  # 使用哪一个货币来支持Vault的经济系统
  type: "金币"

messages:
  prefix: "§a[仓鼠经济] "
  notHasPermission: "§c你没有这个权限!"
  notInputPlayerName: "请输入玩家名称!"
  playerNotFound: "未找到该玩家!"
  notInputCurrencyType: "请输入货币类型!"
  currencyTypeNotFound: "未找到该货币类型!"
  notInputAmount: "请输入货币额度!"
  notInputPayAmount: "请输入转账金额!"
  amountNumberError: "货币额度必须是一个数字!"
  playerCurrencySetSuccess: "货币设置成功! 玩家 %player% 当前 %type% 余额为: %amount%"
  currencyTypeCantTransfer: "%type% 不支持转账!"
  currencyNotEnough: "你的 %type% 不足!"
  paySuccess: "已将 %amount% %type% 转账至 %player% 账户!"
  receivePay: "从 %player% 账户上收到 %amount% %type%."
  seeCurrency: "玩家 %player% 当前货币 %type% 余额为: %amount%"
  pageError: "页码必须是一个大于0的整数!"
  topRankPageHead: "========== %type% 排行榜 第 %page% 页 =========="
  topRankPageItem: "%rank%.%name% %amount%"
  currencyNamePlural: "金币"
  currencyNameSingular: "金币"
  vaultEconomySetError: "服务器经济系统发生了一个错误, 请尝试联系服务器管理员汇报问题!"
