name: HamsterCurrency
version: ${version}
main: cn.hamster3.currency.HamsterCurrency
authors: [ Hamster3 ]
description: 仓鼠的多货币支持
website: https://www.hamster3.cn/

load: STARTUP
api-version: "1.16"

depend:
  - HamsterAPI

softdepend:
  - HasmterService-Bukkit
  - PlaceholderAPI
  - PlayerPoints
  - Vault

commands:
  HamsterCurrency:
    aliases: [ hcurrency, currency ]
  balance:
    aliases: [ bal, seemoney ]
  balanceTop:
    aliases: [ baltop ]
  payMoney:
    aliases: [ pay ]
  economy:
    aliases: [ eco, money ]

permissions:
  currency.import:
    default: op
  currency.give:
    default: op
  currency.take:
    default: op
  currency.set:
    default: op
  currency.reload:
    default: op
  currency.see:
    default: true
  currency.see.other:
    default: op
  currency.top:
    default: op
